name: CI

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  test:
    name: Node.js v${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 22, 24]
    steps:
      - uses: actions/checkout@main

      - name: (env) setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8.15.5

      - name: (env) setup node v${{ matrix.node }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
          check-latest: true

      - name: (env) globals
        run: pnpm add -g oxlint

      - run: pnpm install
      - run: oxlint .
      - run: pnpm run build
      - run: pnpm run typecheck
